# Generated by Django 5.1.7 on 2025-03-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warenname', models.CharField(max_length=50)),
                ('Beschreibung', models.CharField(max_length=150)),
                ('Preis', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
